### ISSUE TITLE
TypeError: Cannot read property 'uxpPlugin' of undefined

### ISSUE THREAD

**Issue by isaiahdaviscom** [isaiahdaviscom/Adobe#4]
[general] Uncaught JS Exception: 
plugins/PluginLoader.js:1:12531
TypeError: Cannot read property 'uxpPlugin' of undefined
    at unloadPlugin (plugins/PluginLoader.js:1:12532)
    at M.handlePluginUnload (plugins/PluginLoader.js:1:11413)
    at uxp://uxp-internal/domjs_scripts.js:2:8784
    at I (uxp://uxp-internal/domjs_scripts.js:2:8676)
    at uxp://uxp-internal/domjs_scripts.js:2:8168
    at O (uxp://uxp-internal/domjs_scripts.js:2:8175)
    at k (uxp://uxp-internal/domjs_scripts.js:2:8953)
    at M._onNativeEvent (uxp://uxp-internal/pluginmanager_scripts.js:1:8626)

**Comment by isaiahdaviscom** [comment]
The above error occurred in the <App> component:

    at App (C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:16:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:18971
update.callback @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:18999
callCallback @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:14207
commitUpdateQueue @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:14228
commitLayoutEffectOnFiber @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:23670
commitLayoutMountEffects_complete @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:24967
commitLayoutEffects_begin @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:24953
commitLayoutEffects @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:24891
commitRootImpl @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:27102
commitRoot @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26961
finishConcurrentRender @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26171
performConcurrentWorkOnRoot @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26088
workLoop @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:33268
flushWork @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:33241
performWorkUntilDeadline @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:33535
(anonymous) @ uxp://uxp-internal/r…scripts_loader.js:2
C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:38 Uncaught ReferenceError: Header is not defined
    at App.render (VM1179 C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:38)
    at finishClassComponent (VM1179 C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:20031)
    at updateClassComponent (VM1179 C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:19977)
    at beginWork (VM1179 C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:21890)
    at beginWork$1 (VM1179 C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:27705)
    at performUnitOfWork (VM1179 C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26839)
    at workLoopSync (VM1179 C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26745)
    at renderRootSync (VM1179 C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26713)
    at recoverFromConcurrentError (VM1179 C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26129)
    at performConcurrentWorkOnRoot (VM1179 C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26029)
render @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:38
finishClassComponent @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:20031
updateClassComponent @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:19977
beginWork @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:21890
beginWork$1 @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:27705
performUnitOfWork @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26839
workLoopSync @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26745
renderRootSync @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26713
recoverFromConcurrentError @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26129
performConcurrentWorkOnRoot @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:26029
workLoop @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:33268
flushWork @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:33241
performWorkUntilDeadline @ C:\Users\<name>\AppData\Local\Packages\Adobe.XD_pc75e8sa7ep4e\TempState\UDTPlugins\react_Developer ID\main.js:33535
(anonymous) @ uxp://uxp-internal/r…scripts_loader.js:2
